# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: 'my-pc'
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  dotNetFramework: 'net9.0'
  dotNetVersion: '9.0.x'
  targetRuntime: 'win-x64'

steps:
  - task: UseDotNet@2
    inputs:
      version: $(dotNetVersion)
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    name: "Build"
    inputs:
      command: 'build'
      projects: '**/FormsIW5.Api.csproj'

  - task: DotNetCoreCLI@2
    name: "Test"
    inputs:
      command: 'test'
      projects: '**/*Tests*.csproj'

  - task: DotNetCoreCLI@2
    name: "Publish"
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/FormsIW5.Api.csproj'
      arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --output $(Build.ArtifactStagingDirectory)/api'
      modifyOutputPath: false
    
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'
      ArtifactName: 'API'
      publishLocation: 'Container'