# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: 'my-pc'
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  dotNetFramework: 'net8.0'
  dotNetVersion: '8.0.x'
  targetRuntime: 'win-x64'
  targetProject: '**/FormsIW5.IdentityProvider.App.csproj'

steps:
  - task: UseDotNet@2
    name: "Install_Environment"
    inputs:
      version: $(dotNetVersion)
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    name: "Build_Identity"
    inputs:
      command: 'build'
      projects: $(targetProject)

  - task: DotNetCoreCLI@2
    name: "Publish_Identity"
    inputs:
      command: 'publish'
      publishWebProjects: true
      projects: $(targetProject)
      arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --output $(Build.ArtifactStagingDirectory)/identity'
      modifyOutputPath: false
    
  - task: PublishBuildArtifacts@1
    name: "Save_Identity_artifact"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/identity'
      ArtifactName: 'Identity'
      publishLocation: 'Container'