# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: 'my-pc'
  vmImage: 'windows-latest'

variables:
  dotNetVersion: '8.0.x'

steps:
  - task: UseDotNet@2
    name: "Install_Environment"
    inputs:
      version: $(dotNetVersion)
      includePreviewVersions: true

  - task: FileTransform@2
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)'
      jsonTargetFiles: '**/appsettings.QA.json'
      
  - task: DotNetCoreCLI@2
    name: "Test_All"
    inputs:
      command: 'test'
      projects: '**/*Tests*.csproj'